import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="bg-slate-500">
          <nav className="flex gap-4">
            <li>
              <Link rel="prefetch" href="/kontakt">
                Kontakt
              </Link>
            </li>
            <li>
              <Link rel="prefetch" href="/">
                Home
              </Link>
            </li>
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
